{"name": "test_login_incorrecto", "status": "passed", "description": "Test para verificar que el login falla con credenciales incorrectas", "start": 1753723443783, "stop": 1753723444802, "uuid": "f9c600b1-b86f-435a-ba05-147f4cdc62c2", "historyId": "1a7c0073c4b528c4a9aa616ca651f6c7", "testCaseId": "1a7c0073c4b528c4a9aa616ca651f6c7", "fullName": "Tests.test_login#test_login_incorrecto", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MacBook-Pro-de-emiliano.local"}, {"name": "thread", "value": "59845-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}], "titlePath": ["Tests", "test_login.py"]}