{"name": "test_login_exitoso", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Locator.wait_for: Timeout 30000ms exceeded.\nCall log:\n  - waiting for locator(\"[data-testid=\\\"titulo-loginn\\\"]\") to be visible", "trace": "page = <Page url='http://localhost:3000/login'>\n\n    def test_login_exitoso(page):\n        \"\"\"Test para verificar un login exitoso con credenciales válidas\"\"\"\n        login_page = LoginPage(page)\n    \n        login_page.ir_a_login()\n        login_page.verificar_url_login()\n>       login_page.verificar_titulo()\n\nTests/test_login.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nPages/LoginPage.py:36: in verificar_titulo\n    self.funcion.validar_texto(self.titulo_login, 'Iniciar sesión')\nFunciones.py:25: in validar_texto\n    elemento.wait_for(state=\"visible\")\n.venv/lib/python3.13/site-packages/playwright/sync_api/_generated.py:17956: in wait_for\n    self._sync(self._impl_obj.wait_for(timeout=timeout, state=state))\n.venv/lib/python3.13/site-packages/playwright/_impl/_locator.py:692: in wait_for\n    await self._frame.wait_for_selector(\n.venv/lib/python3.13/site-packages/playwright/_impl/_frame.py:369: in wait_for_selector\n    await self._channel.send(\n.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:69: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x106212660>\ncb = <function Channel.send.<locals>.<lambda> at 0x1065dbec0>\nis_internal = False, title = None\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False, title: str = None\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(\n            task, \"__pw_stack__\", None\n        ) or inspect.stack(0)\n    \n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal, title)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.wait_for: Timeout 30000ms exceeded.\nE           Call log:\nE             - waiting for locator(\"[data-testid=\\\"titulo-loginn\\\"]\") to be visible\n\n.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:558: TimeoutError"}, "description": "Test para verificar un login exitoso con credenciales válidas", "start": 1753722518973, "stop": 1753722549817, "uuid": "18089fb1-5bb7-4948-bf01-7af507db5966", "historyId": "306654ed1b8e0cd04055ca20a242eb01", "testCaseId": "306654ed1b8e0cd04055ca20a242eb01", "fullName": "Tests.test_login#test_login_exitoso", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MacBook-Pro-de-emiliano.local"}, {"name": "thread", "value": "58168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}], "titlePath": ["Tests", "test_login.py"]}